name: glucose_hf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gradio
  - pytorch
  - optuna
  - tensorboard
  - pip:
    - pandas
    - psutil #compartibility
    - typer
    - darts==0.29.0
    - pmdarima==2.0.4
    - numpy==1.26.4
    - peft
    - transformers
    - datasets
    - python-multipart
    - plotly
    - kaleido
  
  