name: glucose_genie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gradio
  - seaborn
  - pytorch
  - optuna
  - tensorboard
  - pip:
    - pandas
    - psutil #compartibility
    - typer
    - darts==0.29.0
    - pmdarima==2.0.4
    - numpy==1.26.4
    - peft
